name: sac_dino_byol
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.4=h50f4ffc_0
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py312hca03da5_1
  - pip=26.0.1=pyhc872135_0
  - python=3.12.12=h2bfc596_1
  - readline=8.3=h0b18652_0
  - setuptools=80.10.2=py312hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.4.0
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - dm-control==1.0.37
      - dm-env==1.6
      - dm-tree==0.1.9
      - etils==1.13.0
      - filelock==3.24.2
      - fsspec==2026.2.0
      - glfw==2.10.0
      - idna==3.11
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - labmaze==1.0.6
      - lxml==6.0.2
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - mujoco==3.5.0
      - networkx==3.6.1
      - numpy==2.4.2
      - pillow==12.1.1
      - protobuf==6.33.5
      - pyopengl==3.1.10
      - pyparsing==3.3.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.17.0
      - sympy==1.14.0
      - torch==2.10.0
      - torchvision==0.25.0
      - tqdm==4.67.3
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - wrapt==2.1.1
      - zipp==3.23.0
