seed: 42
total_timesteps: 2000000
warmup_steps: 10000
start_training_steps: 10000
checkpoints_dir: "checkpoints/byol"
checkpoints_freq: 50000
update_freq: 2
num_updates_per_batch: 10
action_repeat: 4
frame_stack: 3
image_size: 100
horizon: 250
alpha: 0.2
gamma: 0.99
loss: null
optimizer:
  encoder_lr: 2e-4
  encoder_betas: [0.9, 0.999]
  actor_lr: 2e-4
  actor_betas: [0.9, 0.999]
  critic_lr: 2e-4
  critic_betas: [0.9, 0.999]
  alpha_lr: 1e-4
  alpha_betas: [0.5, 0.999]
  center_mom: 0.996
  target_mom: 0.996
  center_update_freq: 2
  target_update_freq: 2
data:
  global_crop_size: 84
  buffer_capacity: 100000
  batch_size: 1024
