obs_shape: [9, 100, 100]
embed_dim: 50
encoder:
  latent_dim: 64
  num_layers: 4
  hidden_dim: 2048
projection:
  latent_dim: 2048
  num_layers: 3
  num_pseudo_labels: 4096
actor:
  hidden_dim: 2048
critic:
  hidden_dim: 2048
