seed: 42
total_timesteps: 2000000
warmup_steps: 10000
start_training_steps: 10000
checkpoints_dir: "checkpoints/dino"
checkpoints_freq: 50000
update_freq: 2
num_updates_per_batch: 10
action_repeat: 4
frame_stack: 3
image_size: 100
horizon: 250
alpha: 0.2
gamma: 0.99
loss:
  online_temp: 0.1
  target_temp0: 0.07
  target_temp1: 0.04
  target_temp_warmup_timesteps: 600000
  lambda_dino: 0.5

optimizer:
  encoder_lr: 2e-4
  encoder_betas: [0.9, 0.999]
  actor_lr: 2e-4
  actor_betas: [0.9, 0.999]
  critic_lr: 2e-4
  critic_betas: [0.9, 0.999]
  alpha_lr: 1e-4
  alpha_betas: [0.5, 0.999]
  center_mom: 0.996
  target_mom: 0.996
  center_update_freq: 2
  target_update_freq: 2
data:
  num_global: 2
  global_crop_size: 84
  num_local: 6
  local_crop_size: 48
  buffer_capacity: 100000
  batch_size: 1024
