obs_shape: [9, 100, 100]
embed_dim: 50
encoder:
  latent_dim: 32
  num_layers: 4
  hidden_dim: 512
projection:
  latent_dim: 1024
  num_layers: 3
  num_pseudo_labels: 2048
actor:
  hidden_dim: 512
critic:
  hidden_dim: 512
